server:
  port: ${PORT}

spring:
  application:
    name: recipes-app
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '10'
      connection-timeout: '30000'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
      springframework: DEBUG
