spring:
  application:
    name: recipes-app
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '10'
      connection-timeout: '30000'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
      springframework: DEBUG
